// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      // case TargetPlatform.windows:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for windows - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      // case TargetPlatform.linux:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for linux - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyAxDKpxE119CGkaFJJu45M92DLDPUBM2aE',
  //   appId: '1:436426093041:web:f78de1791ec03bb6ed5450',
  //   messagingSenderId: '436426093041',
  //   projectId: 'mongkaset2022',
  //   authDomain: 'mongkaset2022.firebaseapp.com',
  //   storageBucket: 'mongkaset2022.appspot.com',
  //   measurementId: 'G-0M0Q7BX9NH',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: ' AIzaSyD4ixUGjRLHFkyPHA1P2MEYrqtlTnLE6oc',
    appId: '1:700303290325:android:af93f8988eb0497a44575c',
    messagingSenderId: '700303290325',
    projectId: 'project-smart-farm-d4a78',
    storageBucket: 'project-smart-farm-d4a78.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDPmQBqgVacmaPAtLQgcD85L92tZZ4mDLI',
  //   appId: '1:436426093041:ios:441ae99f376cd4cfed5450',
  //   messagingSenderId: '436426093041',
  //   projectId: 'mongkaset2022',
  //   storageBucket: 'mongkaset2022.appspot.com',
  //   iosClientId: '436426093041-lm11p7v54n8fcamve2695hgpd53n2a20.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.loginsystem',
  // );
  //
  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyDPmQBqgVacmaPAtLQgcD85L92tZZ4mDLI',
  //   appId: '1:436426093041:ios:441ae99f376cd4cfed5450',
  //   messagingSenderId: '436426093041',
  //   projectId: 'mongkaset2022',
  //   storageBucket: 'mongkaset2022.appspot.com',
  //   iosClientId: '436426093041-lm11p7v54n8fcamve2695hgpd53n2a20.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.loginsystem',
  // );
}
